version: '3'
services:
  receiver:
    build:
      context: consumer
      dockerfile: consumer.Dockerfile
    container_name: consumer_container
    environment:
      EVENT_HUB_NAME: evh-redditapi-dev-we-tpiuolab-ms-01
      EVENT_HUB_CONNECTION_STR: Endpoint=sb://evhns-dev-hr-tpiuo-ms-01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WOVOO4BrzTTqxF9K+AlYbpOEFgqffjVU9+AEhA0MxUc=
    ports:
      - "443:443"
      - "5671:5671"
      - "5672:5672"

  sender:
    build:
      context: producer
      dockerfile: producer.Dockerfile
    container_name: producer_container
    environment:
      EVENT_HUB_NAME: evh-redditapi-dev-we-tpiuolab-ms-01
      EVENT_HUB_CONNECTION_STR: Endpoint=sb://evhns-dev-hr-tpiuo-ms-01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=WOVOO4BrzTTqxF9K+AlYbpOEFgqffjVU9+AEhA0MxUc=
    ports:
      - "44443:443"
      - "55671:5671"
      - "55672:5672"

